# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Set up JDK 11
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Run package
      run: sbt package
      
